In [ ]:
import pandas as pd

calendar_df = pd.read_csv("./data/calendar.csv.gz")
calendar_df.head(10)

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,3686,2024-06-21,f,$67.00,NaN,31,365
1,3686,2024-06-22,f,$67.00,NaN,31,365
2,3686,2024-06-23,f,$67.00,NaN,31,365
3,3686,2024-06-24,f,$67.00,NaN,31,365
4,3686,2024-06-25,f,$67.00,NaN,31,365
5,3686,2024-06-26,f,$67.00,NaN,31,365
6,3686,2024-06-27,f,$67.00,NaN,31,365
7,3686,2024-06-28,f,$67.00,NaN,31,365
8,3686,2024-06-29,f,$67.00,NaN,31,365
9,3686,2024-06-30,f,$67.00,NaN,31,365

In [4]:
listings_df = pd.read_csv("./data/listings.csv.gz")
listings_df.head(10)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3686,https://www.airbnb.com/rooms/3686,20240621025859,2024-06-21,city scrape,Vita's Hideaway,IMPORTANT NOTES<br />* Carefully read and be s...,We love that our neighborhood is up and coming...,https://a0.muscache.com/pictures/61e02c7e-3d66...,4645,...,4.84,3.91,4.64,NaN,f,1,0,1,0,0.51
1,3943,https://www.airbnb.com/rooms/3943,20240621025859,2024-06-21,city scrape,Historic Rowhouse Near Monuments,You will be staying in high ceiling bedroom w...,This rowhouse is centrally located in the hear...,https://a0.muscache.com/pictures/airflow/Hosti...,5059,...,4.91,4.59,4.76,Hosted License: 5007242201001033,f,5,0,5,0,2.74
2,4197,https://www.airbnb.com/rooms/4197,20240621025859,2024-06-21,city scrape,Capitol Hill Bedroom walk to Metro,This is the middle bedroom upstairs in a resto...,"Our area, the Eastern Market neighborhood of C...",https://a0.muscache.com/pictures/miso/Hosting-...,5061,...,4.98,4.97,4.95,Hosted License: 5007242201000749,f,2,0,2,0,0.33
3,4529,https://www.airbnb.com/rooms/4529,20240621025859,2024-06-21,city scrape,Bertina's House Part One,This is large private bedroom with plenty of...,Very quiet neighborhood and it is easy accessi...,https://a0.muscache.com/pictures/86072003/6709...,5803,...,4.93,4.51,4.83,Exempt,f,2,0,2,0,0.56
4,5589,https://www.airbnb.com/rooms/5589,20240621025859,2024-06-21,previous scrape,Cozy apt in Adams Morgan,This is a 1 br (bedroom + living room in Adams...,"Adams Morgan spills over with hipsters, salsa ...",https://a0.muscache.com/pictures/miso/Hosting-...,6527,...,4.82,4.91,4.44,NaN,f,1,1,0,0,0.53
5,6165,https://www.airbnb.com/rooms/6165,20240621025859,2024-06-21,city scrape,Private Bath & Laundry + Huge Lower Level Suite,DC/Cozy/huge lower level private room/suite w...,16th Street Heights. Safe and quiet. Close to...,https://a0.muscache.com/pictures/152511/513406...,5782,...,4.80,4.53,4.87,NaN,f,1,0,1,0,0.13
6,7103,https://www.airbnb.com/rooms/7103,20240621025859,2024-06-21,city scrape,Lovely guest suite in a quiet but close-in nei...,"Private guest suite with cathedral ceiling, su...",NaN,https://a0.muscache.com/pictures/ad9eb007-05e9...,17633,...,4.90,4.79,4.81,NaN,f,28,28,0,0,0.52
7,11785,https://www.airbnb.com/rooms/11785,20240621025859,2024-06-21,city scrape,Sanctuary near Cathedral,NaN,Our neighborhood is informally known as Cathed...,https://a0.muscache.com/pictures/553101/23b288...,32015,...,4.88,4.84,4.58,NaN,f,4,1,3,0,2.35
8,12442,https://www.airbnb.com/rooms/12442,20240621025859,2024-06-21,city scrape,Peaches & Cream near Cathedral,NaN,There is so much to love in Cathedral Heights!...,https://a0.muscache.com/pictures/miso/Hosting-...,32015,...,4.84,4.82,4.58,NaN,t,4,1,3,0,0.68
9,14218,https://www.airbnb.com/rooms/14218,20240621025859,2024-06-21,city scrape,Quiet Comfort near Nat'l Cathedral,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,32015,...,4.87,4.89,4.67,NaN,f,4,1,3,0,0.65

In [5]:
reviews_df = pd.read_csv("./data/reviews.csv.gz")
reviews_df.head(10)

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,3686,131293,2010-11-01,257234,Callie,Staying with Levita and her wonderful family w...
1,32087,567384,2011-09-25,1192632,Sven,"Very accommodating host, curteous, beautiful l..."
2,32087,1708259,2012-07-14,1321181,Michael,Excellent! Will definitely stay here again. Gr...
3,32087,5389855,2013-06-27,4642537,Yve,Staying at American Guest House was the best d...
4,32087,11115970,2014-03-21,12842454,Crystal,The guest house was very nice - most comfortab...
5,893529,5144488,2013-06-15,2113920,Sunny,I enjoyed staying at Kristie's. She is a great...
6,3686,150766,2010-12-08,255888,Patrick,"Vita is a very welcoming, helpful and friendly..."
7,3686,177749,2011-02-02,366688,Benjamin,"This was my first time using ""airbnb"" and it m..."
8,3686,197451,2011-03-12,213492,T.J.,"First, Vita saved my work week by providing me..."
9,3686,213212,2011-03-30,428455,Pete,Great host! Very welcoming and organised. I st...